FROM dunglas/frankenphp:php8.3

WORKDIR /app

COPY . /app

RUN install-php-extensions pdo_mysql

RUN apt-get update \
    && apt-get install -y \
        git \
        unzip \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php \
    && composer install --no-dev --optimize-autoloader

RUN mkdir -p \
        storage/framework/cache \
        storage/framework/sessions \
        storage/framework/views \
        bootstrap/cache \
    && chmod -R 775 storage bootstrap/cache

EXPOSE 80

CMD ["frankenphp", "php-server", "-r", "public/"]